#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mESPERE \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -c -P /home https://raw.githubusercontent.com/VENHABRABO/SSHPLUS/main/Install/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mBy DANSMX\033[1;36m"|lolcat

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mVERIFICANDO ATUALIZACIONES DISPONIBLES\033[0m\n"|lolcat

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31m ERROR AL CONECTAR CON EL SERVIDOR\n"|lolcat

	echo -ne "\033[1;31m ENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     ESTA SCRIPT ESTA ACTUALIZADO !\033[1;32m\n"|lolcat

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33m MAS INFORMACIÓNES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@DansMx\n"|lolcat

  echo -ne " \033[1;31m ENTER \033[1;33mPresione Enter \033[1;32mMENU!\033[0m"; read

  menu

} || {

  echo -e "  \033[1;36mEXISTE UN NUEVA ACTUALIZACIÓN DISPONIBLE!\033[1;33m\n"|lolcat

  echo -e "  \033[1;33mMAS INFORMACIÓNES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mEDIT:@DansMx\n"

  echo -e "  \033[1;32mACTUALIZAR DETALLES:\033[0m\n"|lolcat

  while read linha; do

    echo -e "  \033[1;37m- \033[1;33m$linha"

  done < "/tmp/att"

  echo " "
  
  figlet "      Actualizar" | lolcat
  echo -ne "  \033[1;32mDESEA ACTUALIZAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read res

  if [[ "$res" = s || "$res" = S ]];then
     figlet "      Actualizando" | lolcat

    echo -e "\n\033[1;32m  INICIANDO ACTUALIZACIÓN..."|lolcat

    sleep 3

    wget https://raw.githubusercontent.com/DanssBot/dansmx/main/Plus > /dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mSCRIPT ACTUALIZADO CON EXITO\033[0m\n"|lolcat

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31mENTER \033[1;33mPresiona Enter para ir al \033[1;32mMENU!\033[0m"; read

    menu

  else

    menu

  fi

}

